package com.speakingcode.creamnsugar.patterns.observer;                                                                                                                                                                                                   
                                                                                                                                                                                                                                                   
import java.util.ArrayList;                                                                                                                                                                                                                        
import java.util.LinkedList;                                                                                                                                                                                                                       
import java.util.List;                                                                                                                                                                                                                             
import java.util.Queue;                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                   
/**                                                                                                                                                                                                                                                
 * A thread-safe implementation of a Subject for the "Observer" pattern.                                                                                                                                                                           
 * An instance of MultiThreadSubject can be safely modified and acted upon by multiple threads.<br>                                                                                                                                                
 * Other classes may extend or compose this class to provide asynchronous callback messaging in                                                                                                                                                    
 * multi-threaded environments.                                                                                                                                                                                                                    
 * @param <ObserverType> The type of the "observers" who will receive callback messages from an                                                                                                                                                    
 * instance of this class.                                                                                                                                                                                                                         
 */                                                                                                                                                                                                                                                
public class MultiThreadSubject<ObserverType>                                                                                                                                                                                                      
{                                                                                                                                                                                                                                                  
    private List<ObserverType> mObservers;                                                                                                                                                                                                         
    private Queue<ObserverType> observersToAdd;                                                                                                                                                                                                    
    private Queue<ObserverType> observersToRemove;                                                                                                                                                                                                 
                                                                                                                                                                                                                                                   
    protected boolean isIteratingObservers = false;                                                                                                                                                                                                
                                                                                                                                                                                                                                                   
    /**                                                                                                                                                                                                                                            
     * Constructs a new MultiThreadSubject object with provided collections for the                                                                                                                                                                
     * observers and the modification queues.                                                                                                                                                                                                      
     * @param mObservers                                                                                                                                                                                                                           
     * @param observersToAdd                                                                                                                                                                                                                       
     * @param observersToRemove                                                                                                                                                                                                                    
     */                                                                                                                                                                                                                                            
    public MultiThreadSubject(List<ObserverType> mObservers,                                                                                                                                                                                       
                Queue<ObserverType>  observersToAdd,                                                                                                                                                                                               
                Queue<ObserverType>  observersToRemove)                                                                                                                                                                                            
    {                                                                                                                                                                                                                                              
        this.mObservers                 = mObservers;                                                                                                                                                                                              
        this.observersToAdd             = observersToAdd;                                                                                                                                                                                          
        this.observersToRemove  = observersToRemove;                                                                                                                                                                                               
    }                                                                 


    /**                                                                                                                                                                                                                                            
     * Constructs a new MultiThreadSubject object                                                                                                                                                                                                  
     */                                                                                                                                                                                                                                            
    public MultiThreadSubject()                                                                                                                                                                                                                    
    {                                                                                                                                                                                                                                              
        this(new ArrayList<ObserverType>(),                                                                                                                                                                                                        
                        new LinkedList<ObserverType>(),                                                                                                                                                                                            
                        new LinkedList<ObserverType>());                                                                                                                                                                                           
    }                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                   
    /**                                                                                                                                                                                                                                            
     * Queues a new observer to be registered to receive callback messages, if it is not already                                                                                                                                                   
     * in the collection.                                                                                                                                                                                                                          
     * @param observer the observer to be registered for callback messages                                                                                                                                                                         
     */                                                                                                                                                                                                                                            
    public void addObserver(ObserverType observer)                                                                                                                                                                                                 
    {                                                                                                                                                                                                                                              
        synchronized(observersToAdd)                                                                                                                                                                                                               
        {                                                                                                                                                                                                                                          
            if (!observersToAdd.contains(observer))                                                                                                                                                                                                
                observersToAdd.add(observer);                                                                                                                                                                                                      
        }                                                                                                                                                                                                                                          
        workQueues();                                                                                                                                                                                                                              
    }   

    /**                                                                                                                                                                                                                                            
     * Queues an observer to be removed from receiving callback messages                                                                                                                                                                           
     * @param observer                                                                                                                                                                                                                             
     */                                                                                                                                                                                                                                            
    public void removeObserver(ObserverType observer)                                                                                                                                                                                              
    {                                                                                                                                                                                                                                              
        synchronized(observersToRemove)                                                                                                                                                                                                            
        {                                                                                                                                                                                                                                          
            if (!observersToRemove.contains(observer))                                                                                                                                                                                             
                observersToRemove.add(observer);                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                          
        workQueues();                                                                                                                                                                                                                              
    }                               

    /**                                                                                                                                                                                                                                            
     * Triggers the MultiThreadSubject to process its queues of observers to be                                                                                                                                                                    
     * registered for and removed from receiving callback messages. This operation will bail                                                                                                                                                       
     * if the collection of observers is being iterated for callback messaging.                                                                                                                                                                    
     */                                                                                                                                                                                                                                            
    public void workQueues()                                                                                                                                                                                                                       
    {                                                                                                                                                                                                                                              
        //bail if iterating through observers                                                                                                                                                                                                      
        if (isIteratingObservers)                                                                                                                                                                                                                  
            return;                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                   
        synchronized(observersToAdd)                                                                                                                                                                                                               
        {                                                                                                                                                                                                                                          
            synchronized(mObservers)                                                                                                                                                                                                               
            {                                                                                                                                                                                                                                      
                for (ObserverType observer : observersToAdd)                                                                                                                                                                                       
                {                                                                                                                                                                                                                                  
                    if (!mObservers.contains(observer))                                                                                                                                                                                            
                        mObservers.add(observer);                                                                                                                                                                                                  
                }                                                                                                                                                                                                                                  
            }                                                                                                                                                                                                                                      
            observersToAdd.clear();                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                   
        synchronized(observersToRemove)                                                                                                                                                                                                            
        {                                                                                                                                                                                                                                          
            synchronized(mObservers)                                                                                                                                                                                                               
            {                                                                                                                                                                                                                                      
                for (ObserverType observer : observersToRemove)                                                                                                                                                                                    
                    mObservers.remove(observer);                                                                                                                                                                                                   
            }                                                                                                                                                                                                                                      
            observersToRemove.clear();                                                                                                                                                                                                             
        }                                                                                                                                                                                                                                          
    } 

    /**                                                                                                                                                                                                                                            
     * Iterates through the observers, calling a callback method on each one.<br>                                                                                                                                                                  
     * The method called is the callBack(ObserverType observer) method of the command parameter, which                                                                                                                                             
     * implements the ICommand interface.                                                                                                                                                                                                          
     * @param command an implementation of the ICommand interface. This implementation provides                                                                                                                                                    
     * a callBack(ObserverType observer) method which can                                                                                                                                                                                          
     */                                                                                                                                                                                                                                            
    public void callbackOnObservers(ICommand<ObserverType> command)                                                                                                                                                                                
    {                                                                                                                                                                                                                                              
        workQueues();                                                                                                                                                                                                                              
        isIteratingObservers = true;                                                                                                                                                                                                               
        synchronized(mObservers)                                                                                                                                                                                                                   
        {                                                                                                                                                                                                                                          
            for (ObserverType observer : mObservers)                                                                                                                                                                                               
            {                                                                                                                                                                                                                                      
                command.callBack(observer);                                                                                                                                                                                                        
            }                                                                                                                                                                                                                                      
        }                                                                                                                                                                                                                                          
        isIteratingObservers = false;                                                                                                                                                                                                              
        workQueues();                                                                                                                                                                                                                              
    }
}                                   